# Generated by Django 2.2.6 on 2020-04-04 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park_Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Name', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Property_Description', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Property_Guest_Capacity', models.IntegerField(blank=True, null=True)),
                ('Property_Location', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Indoor', max_length=50)),
                ('Slot', models.CharField(blank=True, default='2 hours', max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Property_Image', models.ImageField(default='Images/park1.jpg', upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Park_Name', models.CharField(default=' ', max_length=50)),
                ('Park_Address', models.CharField(blank=True, default=' ', max_length=250, null=True)),
                ('County', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Park_Image', models.ImageField(default='Images/park1.jpg', upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_From', models.DateTimeField(blank=True, null=True)),
                ('Date_To', models.DateTimeField(blank=True, null=True)),
                ('Team_Name', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Team_Size', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Park_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Parks')),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Park_Properties')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_Amount', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Trans_Time_Date', models.DateTimeField(blank=True, null=True)),
                ('Trans_Type', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Transaction_Token', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Reservation')),
                ('Park_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Parks')),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Park_Properties')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_TimeDate', models.DateTimeField(blank=True, null=True)),
                ('Property_Status_Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Expenses', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Maintenance_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Park_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Parks')),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Park_Properties')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability_Start_Time', models.DateTimeField(blank=True, null=True)),
                ('Availability_End_time', models.DateTimeField(blank=True, null=True)),
                ('Park_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Parks')),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Park_Properties')),
            ],
        ),
        migrations.AddField(
            model_name='park_properties',
            name='Park_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Parks'),
        ),
    ]
