# Generated by Django 2.2.6 on 2020-04-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aafieldapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Team_Name',
            new_name='Slot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date_From',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date_To',
        ),
        migrations.AddField(
            model_name='property_status',
            name='Reservation_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aafieldapp.Reservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='Event_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Status',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='park_properties',
            name='Property_Image',
            field=models.ImageField(default='Images/pool.jpg', upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='parks',
            name='Park_Image',
            field=models.ImageField(default='Images/park2.jpg', upload_to='Images'),
        ),
    ]
