# Generated by Django 2.2.6 on 2020-04-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aafieldapp', '0003_auto_20200408_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_status',
            name='Reservation_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='aafieldapp.Reservation'),
        ),
    ]
