# Generated by Django 2.2.6 on 2020-04-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aafieldapp', '0005_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park_properties',
            name='Property_Image',
            field=models.ImageField(default='Images/pool.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='parks',
            name='Park_Image',
            field=models.ImageField(default='Images/park2.jpg', upload_to=''),
        ),
    ]
