# Generated by Django 2.2.6 on 2020-04-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aafieldapp', '0006_auto_20200424_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='Park_Name',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='Property_Name',
        ),
        migrations.DeleteModel(
            name='Property_Availability',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
